export const cypressCommonConfig: Cypress.ConfigOptions<any> = {
  retries: {
    runMode: 2,
    openMode: 0,
  },
  reporter: "cypress-multi-reporters",
  // reporter: "cypress-sonarqube-reporter"
  // reporter: 'cypress-mochawesome-reporter',
  reporterOptions: {
    reporterEnabled: "cypress-sonarqube-reporter, cypress-mochawesome-reporter, mocha-junit-reporter",
    // reporterEnabled: "cypress-mochawesome-reporter, mocha-junit-reporter",
    ignoreVideos: false,
    videoOnFailOnly: true,
    quiet: false,
    debug: true,
    // mochaawesome config - https://github.com/adamgruber/mochawesome-report-generator#options
    reportPageTitle: 'cypress-report',
    reportFilename: "[datetime]-[name]-report",
    timestamp: "longDate",
    charts: true,
    inline: true,
    autoOpen: false,
    // overwrite: true,
    showPassed: true,
    showFailed: true,
    showSkipped: true,
    showPending: true,
    showHooks: true,
    saveJson: false,
    saveHtml: true,
    code: true,
    // embeddedScreenshots: true,
    // inlineAssets: true,
    // saveAllAttempts: true,
    // configFile: "reports.config.json",
    mochaJunitReporterReporterOptions: {
      mochaFile: "./results/junit/results-[hash].xml",
      testsuitesTitle: false,
      toConsole: true,
      useFullSuiteTitle: true,
      // suiteTitleSeparatedBy: ".",
      reportTitle: "Cypress Tests",
    },
    mochawesomeReporterOptions: {
        reportDir: "./results/mochawesome",
		quiet: true,
		overwrite: false,
		html: false,
		json: false,
		reportFilename: "mochawesome",
		timestamp: "longDate",
		reportTitle: "Cypress Tests",
		inlineAssets: true
	},
    cypressMochawesomeReporterReporterOptions: {
      reportDir:"./results/mochawesome",
      charts: true,
      json: false,
      saveJson: false,
      saveHtml: true,
    },
    cypressSonarqubeReporterReporterOptions: {
      reportDir: "./results/sonarqube",
      reportFilename: "sonarqube-report",
      overwrite: true
    }
  },
  includeShadowDom: true,
  watchForFileChanges: false,
  animationDistanceThreshold: 5,
  chromeWebSecurity: false,
  blockHosts: null,
  clientCertificates: [],
  defaultCommandTimeout: 4000,
  downloadsFolder: './results/downloads',
  env: {
    PORT: process.env.PORT,
    USERNAME: process.env.USERNAME,
    allure: true,
    allureLogCyCommands: true,
    grepFilterSpecs: true,
    grepOmitFiltered: true,
    visualRegressionBaseDirectory: "cypress/snapshot/base",
    visualRegressionDiffDirectory: "cypress/snapshot/diff",
    visualRegressionType: "regression",
  },
  execTimeout: 60000,
  experimentalStudio: false,
  experimentalWebKitSupport: false,
  fileServerFolder: '',
  fixturesFolder: 'cypress/fixtures',
  hosts: null,
  modifyObstructiveCode: true,
  numTestsKeptInMemory: 50,
  pageLoadTimeout: 30000,
  port: null,
  projectId: null,
  redirectionLimit: 20,
  taskTimeout: 60000,
  requestTimeout: 5000,
  responseTimeout: 30000,
  screenshotOnRunFailure: true,
  screenshotsFolder: './results/screenshots',
  scrollBehavior: 'top',
  trashAssetsBeforeRuns: true,
  userAgent: null,
  video: false,
  videoCompression: false,
  videosFolder: './results/videos',
  viewportHeight: 660,
  viewportWidth: 1000,
  waitForAnimations: true
}