export const cypressCommonConfig: Cypress.ConfigOptions<any> = {
  retries: {
    runMode: 2,
    openMode: 0,
  },
  reporter: "cypress-multi-reporters",
  // reporter: "cypress-sonarqube-reporter"
  // reporter: 'cypress-mochawesome-reporter',
  reporterOptions: {
    reporterEnabled: "cypress-sonarqube-reporter, mochawesome, cypress-mochawesome-reporter, mocha-junit-reporter",
    ignoreVideos: false,
    videoOnFailOnly: true,
    quiet: false,
    debug: true,
    // mochaawesome config - https://github.com/adamgruber/mochawesome-report-generator#options
    reportPageTitle: 'cypress-report',
    reportFilename: "[datetime]-[name]-report",
    timestamp: "longDate",
    charts: true,
    inline: true,
    autoOpen: false,
    overwrite: true,
    showPassed: true,
    showFailed: true,
    showSkipped: true,
    showPending: true,
    showHooks: true,
    saveJson: true,
    saveHtml: true,
    code: true,
    embeddedScreenshots: true,
    inlineAssets: true,
    saveAllAttempts: true,
    // configFile: "reports.config.json",
    mochaJunitReporterReporterOptions: {
      mochaFile: "cypress/results/junit/results-[hash].xml",
      testsuitesTitle: false,
      toConsole: true,
      useFullSuiteTitle: true,
      // suiteTitleSeparatedBy: ".",
      reportTitle: "Cypress Tests",
    }
  },
  includeShadowDom: true,
  watchForFileChanges: false,
  animationDistanceThreshold: 5,
  chromeWebSecurity: false,
  blockHosts: null,
  clientCertificates: [],
  defaultCommandTimeout: 4000,
  downloadsFolder: 'outputs/downloads',
  env: {
    PORT: process.env.PORT,
    USERNAME: process.env.USERNAME,
  },
  execTimeout: 60000,
  experimentalStudio: false,
  experimentalWebKitSupport: false,
  fileServerFolder: '',
  fixturesFolder: 'cypress/fixtures',
  hosts: null,
  modifyObstructiveCode: true,
  numTestsKeptInMemory: 50,
  pageLoadTimeout: 30000,
  port: null,
  projectId: null,
  redirectionLimit: 20,
  taskTimeout: 60000,
  requestTimeout: 5000,
  responseTimeout: 30000,
  screenshotOnRunFailure: true,
  screenshotsFolder: 'outputs/screenshots',
  scrollBehavior: 'top',
  trashAssetsBeforeRuns: true,
  userAgent: null,
  video: false,
  videoCompression: false,
  videosFolder: 'outputs/videos',
  viewportHeight: 660,
  viewportWidth: 1000,
  waitForAnimations: true
}